name: Android MVP Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter Clean
        working-directory: apps/mobile
        run: flutter clean

      - name: Install dependencies
        working-directory: apps/mobile
        run: flutter pub get

      - name: Generate Build Version
        run: |
          echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Print Build Number
        run: |
          echo "BUILD_NUMBER=$BUILD_NUMBER"

      - name: Print pubspec version
        working-directory: apps/mobile
        run: |
          grep version pubspec.yaml

      - name: Build User APK
        working-directory: apps/mobile
        run: |
          flutter build apk --release \
            --build-number=$BUILD_NUMBER \
            --dart-define=GOVERNANCE_BUILD=false

      - name: Print APK info
        run: |
          ls -lh apps/mobile/build/app/outputs/flutter-apk/

      - name: Save User APK
        run: mv apps/mobile/build/app/outputs/flutter-apk/app-release.apk apps/mobile/build/app/outputs/flutter-apk/app-user-release.apk

      - name: Build Governance APK
        working-directory: apps/mobile
        run: |
          flutter build apk --release \
            --build-number=$BUILD_NUMBER \
            --dart-define=GOVERNANCE_BUILD=true


      - name: Save Governance APK
        run: mv apps/mobile/build/app/outputs/flutter-apk/app-release.apk apps/mobile/build/app/outputs/flutter-apk/app-governance-release.apk

      - name: Upload User APK
        uses: actions/upload-artifact@v4
        with:
          name: twofun-user-apk
          path: apps/mobile/build/app/outputs/flutter-apk/app-user-release.apk

      - name: Upload Governance APK
        uses: actions/upload-artifact@v4
        with:
          name: twofun-governance-apk
          path: apps/mobile/build/app/outputs/flutter-apk/app-governance-release.apk
